# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PHPCodeGuide
email: hello@phptraining.com
description: >- # this means to ignore newlines until "baseurl:"
  PHPCodeGuide.com is a quick reference guide for PHP Language.
  It helps to provide a basic syntax, PHP Code Samples and Manual Reference
  that you can refer during PHP coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phpcodeguide.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: phptrainingdotcom
github_username:  phptrainingdotcom

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]


# Build settings
markdown: kramdown
#theme: minima
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Contribute on GitHub":
    - "//github.com/phptrainingdotcom/phpcodeguide"

